# Generated by Django 5.1.1 on 2024-10-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folioapp', '0002_portefolio_alter_myprofile_photo_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='portefolio',
            name='link',
            field=models.CharField(default='http://ec2-18-191-190-237.us-east-2.compute.amazonaws.com/', max_length=150),
            preserve_default=False,
        ),
    ]
